# Generated by Django 6.0.3 on 2026-03-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_status', models.CharField(choices=[('HR', 'High Risk'), ('MR', 'Medium Risk'), ('LR', 'Low Risk')], default='MR', max_length=2)),
                ('risk_description', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('employees', models.ManyToManyField(to='core.employee')),
                ('risks', models.ManyToManyField(to='core.risk')),
            ],
        ),
    ]
