# Generated by Django 6.0.3 on 2026-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
