# Generated by Django 6.0.3 on 2026-04-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='risks',
        ),
        migrations.AddField(
            model_name='risk',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('FR', 'Functional'), ('NFR', 'Non-functional')], default='FR', max_length=3),
        ),
    ]
