# Generated by Django 6.0.3 on 2026-04-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_risks_risk_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffortEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort_type', models.CharField(choices=[('AN', 'Requirement Analysis'), ('DE', 'Design'), ('CO', 'Coding'), ('TE', 'Testing'), ('PM', 'Project Management')], max_length=2)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efforts', to='core.requirement')),
            ],
        ),
    ]
